---
title: "Modelle aufstellen"
---

> Diese Regeln wurden mit Fokus auf Pflanzenbauwissenschaften aufgestellt. [Quelle hier](https://www.gpw.uni-kiel.de/de/jahrestagung/pre-conference-workshops/pre-conference-workshop-2016/workshop-2016-1)

# Wann ist ein Faktor zufällig?
Ein Faktor ist zufällig, wenn

- die beobachteten Faktorstufen eine Zufallsstichprobe einer definierten Gesamtpopulation darstellen

- wenn es eine Randomisationseinheit darstellt

- wenn er mit einem anderen zufälligen Faktor "gekreuzt" ist. 

Ansonsten ist ein Faktor meist fest.

Ein zufälliger Effekt ist dann am sinnvollsten, wenn er viel Faktorstufen hat. Dementsprechend ist er nicht unbedingt als zufälliger Effekt geeignet, wenn zu wenig Faktorstufen gemessen wurden. "*You usually can’t use random effects when the grouping variable has fewer than five levels, and random effects variance estimates are unstable with fewer than eight levels, because you are trying to estimate a variance from a very small sample.*" ([Fox, Negrete-Yankelevich, and Sosa 2014](https://global.oup.com/academic/product/ecological-statistics-9780199672554?cc=de&lang=en&), pp. 311-315)

Ein Faktor **muss** außerdem fest sein, wenn die Faktorstufen miteinander verglichen werden sollen.

**Beispiel:** _In Hessen werden mehrere Versuche angelegt um die Leistung von mehreren Sorten zu untersuchen. Die Gesamtpopulation der Umwelten ist Hessen, wobei die Versuchsstandorte eine zufällige Stichprobe daraus sind. Der Faktor Umwelt ist also zufällig. Da ganz bestimmte Sorten geprüft werden und deren Mittelwerte berechnet und miteinander verglichen werden sollen, ist der Faktor Sorte fest. Wenn ein Wechselwirkungseffekt zwischen Umwelt und Sorte ins Modell aufgenommen wird, ist dieser auch zufällig, da Umwelt bereits zufällig ist._

Weitere interessante Diskussionen [hier](https://stats.stackexchange.com/questions/4700/what-is-the-difference-between-fixed-effect-random-effect-and-mixed-effect-mode)