---
title: "Versuchsdesigns"
---

# Vorwissen

Wer einen Versuch durchführen möchte, tut dies um eine (Versuchs)frage zu beantworten. Konkret muss dafür entschieden werden wie viele und welche *Behandlungsfaktoren* (auch *Prüffaktoren* oder einfach *Behandlungen*) in dem Versuch untersucht werden sollen (z.B. 2: Sorten und Düngemittel). Behandlungsfaktoren sind die Einflussfaktoren, deren Wirkung auf die interessierende Zielvariablen untersucht werden soll. Dann muss für jeden der Behandlungsfaktoren entschieden werden entschieden werden, wie viele welche Faktorstufen dieses Faktors untersucht werden sollen (z.B. die 3 Sorten A, B und C die 2 Dünger 1 und 2). Bereits an diesem Punkt ist also klar wie viele kombinierte Behandlungsstufen untersucht werden sollen (z.B. die 6 A1, B1, C1, A2, B2, C2). Diesen Teil eines Versuchs wollen wir hier als **treatment part** bezeichnen.

Dieses Kapitel geht davon aus, dass der Leser vertraut ist mit Prinzipien der Versuchsplanung: *Wiederholung* (muss), *Randomisation* (muss) und "*Blockbildung* (kann). Außerdem sollte klar sein, dass *Randomisationseinheiten* denjenigen Einheiten sind, denen die Stufen der Behandlungsfaktoren gemäß des verwendeten Versuchsplans zufällig zuordnet werden (z.B. das Tier oder die Parzelle). Alles was mit dem Versuchsdesign zu tun hat, wollen wir hier als den **design part** bezeichnen.

# Completely Randomized Design (CRD)

Das simpelste Versuchsdesign ist die vollständig randomisierte Anlage, welche ganz ohne Blöcke auskommt. Wie der Name sagt, werden lediglich die gewählte Anzahl Wiederholungen (z.B. 3) jeder Behandlungsstufe (in unserem Beispiel 3 x 6 = 18) komplett zufällig den Randomisationseinheiten zugeordnet. Im *design part* des Modells gibt es hier keinen Effekt [Siehe Beispiel hier](1F_crd.html)

# Complete Blocks 

Anstatt die Behandlungen völlig zufällig auf die Randomisationseinheiten zu randomisieren, ist es oft besser, eine Blockbildung vorzunehmen. *Besser* meint hier, dass der Vergleich der Behandlungsstufen mit einer höheren Genauigkeit durchgeführt werden kann. Das hängt damit zusammen, dass der Versuchsfehler der Varianzanalyse bei einer Blockanlage in der Regel kleiner ist als bei einer vollständig randomisierten Anlage, sofern Blockunterschiede bestehen. **Blöcke sollten dabei so erstellt werden, dass innerhalb eines jeden Blocks möglichst homogene Bedingungen herrschen.** Die Randomisation findet dann getrennt für jeden Block statt. Wenn dabei die Randomisationseinheiten so zu einem Block zusammengefasst werden, dass jede Behandlungsstufe einmal in jedem Block vorkommt, dann spricht man von vollständigen Blöcken. Desweiteren werden vollständige Blöcke auch oft als *Wiederholungen* bezeichnet, da in der Tat jede Behandlungsstufe einmal pro Wiederholung vorkommt. Es muss aber unbedingt klar sein, dass auch ein CRD Versuch "Wiederholungen" hat, diese aber nicht als Blöcke angelegt waren.

## Randomized Complete Block Design (RCBD)

Solch ein einfaches und beliebtes Design ist die randomisierte vollständige Blockanlage. Wichtig ist dabei zu realisieren, dass das "vollständig" hier zu dem Wort "Block" gehört und nicht zu dem Wort "randomisiert", wie es noch bei der "vollständig randomisierten Anlage" der Fall war. Tatsächlich wird ja hier eben nicht vollständig randomisiert, sondern getrennt pro Block. Im *design part* des Modells gibt es hier einen festen Effekt für die vollständigen Blöcke. [Siehe Beispiel hier](1F_rcbd.html)

## Latin Square

Der Vollständigkeit halber soll an diesem Punkt das *Lateinische Quadrat* als weiteres Versuchsdesign erwähnt werden. Diese Anlage ist z.B. dann sinnvoll, wenn es zwei Störgradienten gibt, die orthogonal zueinander ausgerichtet sind (z.B. Nord-Süd Feuchtigkeitsgefälle und Ost-West Nährstoffgefälle im Boden des Fersuchsfelds). Die Randomisationseinheiten werden dann wie der Name sagt als ein Quadrat angelegt, sodass es zwangsweise genau so viele Zeilen wie Spalten gibt. Es ist dann möglich so zu randomisieren, dass sowohl jede Spalte, als auch jede Zeile ein vollständiger Block ist (Sudoku-ähnlich). Im *design part* des Modells gibt es hier je einen festen Effekt für die vollständigen Zeilen-Blöcke und die vollständigen Spalten-Blöcke.

# Incomplete Blocks

Wie schon gesagt sollte ein Block so gebildet werden, dass für die in ihm gruppierten Randomisationseinheiten möglichst gleiche Bedingungen herrschen. In unserem Beispiel mit den 6 Behandlungskombinationen kann man sich gut vorstellen, dass diese auf einem recht homogenen Bereich des Versuchsfeldes gruppiert werden können. Nun könnte es ja aber auch der Fall sein, dass man sehr viel mehr als nur 6 Behandlungsstufen untersuchen möchte. Dann wird es schnell schwierig so große, homogene Abschnitte für die große Anzahl Parzellen eines vollständigen Blocks zu finden. In solch einem Fall ist es wiederum oft günstiger (zusätzlich) unvollständige Blöcke zu bilden. Wenn man dabei immer mehrere unvollständige Blöcke zu einem vollständigen Block zusammenfassen kann, dann spricht man von einem *resolvable* Design.

## Alpha-design 

Ein sehr gängiges *resolvable* Design mit unvollständigen Blöcken ist das $\alpha$-design (=die gängigste und flexibelste Form der *lattice* Designs/*Gitteranlagen*). Hier werden die vollständigen Blöcke jeweils nochmal in unvollständige Teilblöcke unterteilt, die alle dieselbe Größe haben. Würden wir also beispielhaft von 24 Randomisationseinheiten pro vollständigem Block ausgehen, dann könnte man diesen in 2 unvollst. Blöcke a 12 Parzellen, 3 unvollst. Blöcke a 8 Parzellen, 4 unvollst. Blöcke a 6 Parzellen usw. unterteilen um ein $\alpha$-design zu erhalten. Im *design part* des Modells gibt es hier je einen festen Effekt für die vollständigen Blöcke und einen zufälligen Effekt für die unvollständigen Blöcke. [Siehe Beispiel hier](1F_alpha.html)

## Split-plot design

Split-plot designs (*Spaltanlagen*) bieten sich an, wenn in einem Experiment mehrere Behandlungsfaktoren untersucht werden sollen, die unterschiedlich schwer zu randomisieren sind. [Siehe Beispiel hier](2F_splitplot.html). In jedem vollständigen Block werden die Stufen des schwer zu randomisiernden Behandlungsfaktors zu einem *main plot* zusammengefasst und innerhalb jedes main plots werden dann die Stufen des leichter zu randomisiernden Behandlungsfaktors angelegt (*sub-plots*). Demnach sind zwei aufeinanderfolgende Randomisationen nötig, die beide wie in einem RCBD ablaufen: Innerhalb jeder Wiederholung wird der main plot Faktor randomisiert und innerhalb jedes main plots wird der sub-plot Faktor randomisiert. Der Vorteil von split-plot designs ist also, dass die praktische Durchführung so erleichtert/ermöglicht wird. Der Nachteil ist, dass die Anzahl der Freiheitsgrade reduziert und somit der Restfehler erhöht wird, sodass der angestrebte Vergleich der Behandlungsstufen an Genauigkeit verliert. Generell ist der Vergleich der sup-plot Faktorstufen genauer als der der main plot Faktoren. Was hier beschrieben wurde ist aber lediglich die häufigste Version eines solchen designs - es gibt nämlich nicht *das* split-plot design. Es kann zum Beispiel auch sein, dass 3 Behandlungsfaktoren jeweils unterschiedlich schwer zu randomisieren sind, sodass es main plots, sub-plots und sub-sub-plots gibt. Das Prinzip bleibt allerdings immer dasselbe. Im *design part* des Modells gibt es hier je einen festen Effekt für die vollständigen Blöcke und einen zufälligen Effekt für die main plots (und falls es sub-sub-plots gibt auch noch einen zufälligen Effekte für die sub-plots). Generell gibt es also einen zufälligen Effekt für jede Randomisationseinheit.

## Streifenanlagen

Streifenanlagen (*split-block* oder *strip-plot* designs) können hinsichtlich der praktischen Erleichterung als eine weitere Steigerung der split-plot designs angesehen werden. Allerdings werden wieder die Freiheitsgrade reduziert, was zu einem größeren Restfehler und demnach ungenaueren Vergleichen der Behandlungsstufen führt. 

...to be continued...


 







