---
title: "Nicht-normalverteilte Daten"
---

Neben normalverteilten Daten wie z.B. dem Ertrag als Zielvariable, gibt es auch z.B. binomial- oder poissonverteilte Daten. Der wichtigste Unterschied hier besteht darin, dass wir bei der Modellierung nicht davon ausgehen können, dass die Fehler normalverteilt sind. Die einfachen linearen Modelle und übrigens auch lineare gemischte Modelle nehmen allerdings normalverteilte Fehler an und um diese Vorraussetzung zu prüfen betrachten wir schließlich die Residuenplots. Wenn nun also ein Modell für solche Daten angepasst wird, der QQ-Plot aber schlichtweg nicht auf normalverteilte Fehler schließen lässt, sollte nicht mit dem zugehörigen Modell fortgefahren werden. 

## Datentransformation

In solchen Fällen kann versucht werden die Daten (*i.e.* die Zielvariable) zu transformieren und das Modell erneut anzupassen. Wenn sich der QQ-Plot auf diese Weise verbessert, können so schlichtweg die transformierten Daten mit dem einfachen linearen (gemischten) Modell ausgewertet werden. Gängige Transformationen sind die log- und Wurzel-Transformation. Praktisch bedeutet das tatsächlich, dass man nicht `y`, sondern `log(y)` oder `sqrt(y)` modelliert. Dementsprechend liefert am Ende `emmeans()` auch adjustierte Mittelwerte für die Wurzel aus dem Ertrag beispielsweise. Das scheint nicht zielführend zu sein, jedoch ist es eben doch genau das, da auch so signifikante Behandlungseffekte mittels ANOVA gefunden werden. Desweiteren können auch die paarweisen Mittelwertvergleiche durchgeführt werden. Schließlich können die Mittelwerte am Ende auch einfach rücktransformiert werden, also bei z.B. die `sqrt(y)` Mittelwerte quadriert werden. Wichtig ist eben, dass die Modellvoraussetzunge erfüllt sind.

## Generalisierte lineare (gemischte) Modelle

Sollte man keine Datentransformation finden, die die gewünschten Modellvoraussetzungen erfüllt, können auch **generalisierte lineare Modelle** verwendet werden. Diese Modelle sind flexibler, da sie auch andere Verteilungen als die Normalverteilung, sowie Varianzheterogenität zulassen. Demnach kann man sich voll auf die Erzielung der Linearität/Additivität konzentrieren. In die Klasse der GLMs fallen eine ganze Reihe gängiger Modelle, z.B. die Logit- und Probit-Regression für binomialverteilte Daten oder die loglinearen Modelle für poissonverteilte Daten. Die für uns "normalen" Modelle sind also ein Sonderfall der generalisierten Modelle, die normalverteilte Fehler mit homogener Varianz annehmen.

Es soll gesagt sein, dass in der Praxis die oben beschrieben Schritte manchmal auch übersprungen werden und einfach direkt ein generalisiertes lineares Modell für bestimmte Datentypen angepasst wird. So z.B. für **Prozentwerte (binomialverteilt)** oder **nach oben offene Zähldaten (poissonverteilt)**.

### Binomialverteilte Daten
logit link funktion

### Poissonverteilte Daten
log link funktion

binomial(link = "logit")
gaussian(link = "identity")
Gamma(link = "inverse")
inverse.gaussian(link = "1/mu^2")
poisson(link = "log")
quasi(link = "identity", variance = "constant")
quasibinomial(link = "logit")
quasipoisson(link = "log")