---
title: "Messwiederholungen"
output: 
  html_document:
    includes:
      after_body: footer.html 
---

# Messwiederholung $\ne$ echte Wiederholung 
Messwiederholungen (*Repeated Measures*) sind klar zu trennen von echten Wiederholungen (*Replicates*). Bei echten Wiederholungen werden beispielsweise Blutwerte von mehreren Mäusen, die die gleiche Behandlung erfahren haben, bestimmt. Bei Messwiederholungen wird der Blutwert ein und derselben Maus mehrfach genommen, nämlich über Zeit hinweg - also beispielsweise jede Woche. Natürlich kann es in einem Experiment sowohl echte, als auch Messwiederholungen geben: Mehrere Mäuse werden über mehrere Woche beprobt. Wichtig ist aber, dass Messwiederholungen eine Besonderheit darstellen, die in der statistischen Auswertung der Daten berücksichtig werden sollte.

# Die Besonderheiten
Wir wollen zuerst von einem Versuch ausgehen, der nur echte Wiederholungen hat - also beispielsweise ein Versuch mit 10 Mäusen, die aber nur ein einziges Mal beprobt wurden. Eine der Annahmen, die bzgl. der so erhobenen 10 Datenpunkte getroffen wird damit beispielsweise eine ANOVA zulässig ist, ist die Unabhängigkeit der Datenpunkte (streng genommen: der Fehler der Datenpunkte). Unabhängig meint, dass die Datenpunkte nicht miteinander auf eine bestimmte Weise korreliert sind. Unter anderem das Randomisieren der echten Wiederholungen sorgt dafür, dass dies auch gegeben ist. 

Nun gehen wir aber davon aus, dass Messwiederholungen durchgeführt wurden indem die 10 Mäuse jeweils 3 Mal mit wöchtenlichem Abstand beprobut wurden. Es ist offensichtlich, dass immer die Messwerte, die von derselben Maus stammen, sich ähnlich sind. Zumindest dürften sich die Messwerte derselben Maus an verschiedenen Zeitpunkten in der Regel ähnlicher sein, als die Messwerte verschiedener Mäuse. Spätestens wenn man sich vorstellt zwei Beprobungen mit nur einer Minute Abstand durchzuführen, wird klar, dass die Werte ein und derselben Maus untereinander korreliert sein dürften.

Darüber hinaus wird oft nicht nur davon ausgegangen, **dass** die Werte derselben Maus korreliert sind, sondern auch noch **wie**: Nämlich so, dass je weniger Zeit vergangen ist, desto ähnlicher sind sich die Werte (*serial correlation*). In diesem Beispiel mit den 3 Messungen mit je einer Woche Abstand würde man also davon ausgehen, dass sich Werte aus Woche 1 & 2 oder 2 & 3 ähnlicher sind als Werte aus den Wochen 1 & 3, da bei letzteren mehr Zeit zwischen den Beprobungen vergangen ist.

Dies deutet außerdem auf eine weitere Einschränkung hin: Die Messwiederholungen können nicht randomisiert werden. Sicherlich mag dies offensichtlich erscheinen, da Beprobungen über mehrere Wochen eben nur in der von der Zeit festgelegten Reihenfolge stattfinden können (*i.e.* zuerst Woche 1, danach Woche 2 usw.), aber es muss klar sein, dass auch dies eine Besonderheit von Messwiederholungen ist und eben im Kontrast zu echten Wiederholungen steht.

Genau das widerspricht der Annahme der Unabhängigkeit und rät somit davon ab eine einfache ANOVA für die Daten durchzuführen. Da Experimente mit Messwiederholungen allerdings oft gewollt sind und in bestimmten Bereichen Gang und Gebe sind, wurde auch in der Statistik viel für die Auswertung solcher Daten getan.

# 

