<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Stichprobenplanung</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/lumen.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
      </style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 54px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h2 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h3 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h4 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h5 {
  padding-top: 59px;
  margin-top: -59px;
}
.section h6 {
  padding-top: 59px;
  margin-top: -59px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">crashcouRse</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    R Anwendung
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="datr_importexport.html">Import &amp; Export</a>
    </li>
    <li>
      <a href="datr_descriptivestats.html">Deskriptive Statistik</a>
    </li>
    <li>
      <a href="datr_desplot.html">desplot package</a>
    </li>
    <li>
      <a href="datr_multipledat.html">Loops &amp; Listen</a>
    </li>
    <li>
      <a href="datr_moreadvanced.html">Weitere Tipps</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Auswertungen
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="1n_drinks.html">Korrelation &amp; Regression</a>
    </li>
    <li>
      <a href="outlier_vision.html">Ausreisser (Korr &amp; Reg pt.2)</a>
    </li>
    <li>
      <a href="1f_crd.html">1F crd</a>
    </li>
    <li>
      <a href="1f_rcbd.html">1F rcbd</a>
    </li>
    <li>
      <a href="1f_alpha.html">1F alpha</a>
    </li>
    <li>
      <a href="2f_rcbd.html">2F rcbd</a>
    </li>
    <li>
      <a href="2f_splitplot.html">2F split-plot</a>
    </li>
    <li>
      <a href="1f_augmented_blockfixorrandom.html">1F augmented</a>
    </li>
    <li>
      <a href="1f_rcbd_messwdh.html">1F rcbd Messwiederholungen</a>
    </li>
    <li>
      <a href="1f_rcbd_binomial.html">1F rcbd Prozentwerte</a>
    </li>
    <li>
      <a href="1f_latsq_poisson.html">1F lat square Zählwerte</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Statistik
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="stat_korrelation.html">Korrelation</a>
    </li>
    <li>
      <a href="stat_regression.html">Regression</a>
    </li>
    <li>
      <a href="appendix_designs.html">Versuchsdesigns</a>
    </li>
    <li>
      <a href="appendix_posthoc.html">ANOVA &amp; Post Hoc</a>
    </li>
    <li>
      <a href="appendix_interaktionen.html">Interaktionen</a>
    </li>
    <li>
      <a href="stat_adjmeans.html">Adj. Mittelwerte</a>
    </li>
    <li>
      <a href="stat_pvalue.html">p-Werte &amp; Signifikanz</a>
    </li>
    <li>
      <a href="stat_gemischtemodelle.html">Gemischte Modelle</a>
    </li>
    <li>
      <a href="appendix_kovarstrukt.html">Kovarianzstrukturen 1</a>
    </li>
    <li>
      <a href="3f_met_regions.html">Kovarianzstrukturen 2</a>
    </li>
    <li>
      <a href="intro_glm_carrot.html">Nicht-Normalverteilte Daten</a>
    </li>
    <li>
      <a href="stat_logisticregression.html">Logistische Regression</a>
    </li>
    <li>
      <a href="appendix_modelrules.html">Modelle aufstellen</a>
    </li>
    <li>
      <a href="stat_samplesize.html">Stichprobenplanung</a>
    </li>
  </ul>
</li>
<li>
  <a href="kontaktseite.html">Kontakt</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Stichprobenplanung</h1>

</div>


<div id="fragestellung" class="section level1">
<h1>Fragestellung</h1>
<p>Es ist bekannt, dass etwa 1% aller Männer rot-blind (protanop) sind. Es wird vermutet, dass protanope Autofahrer häufiger Auffahrunfälle verursachen als nicht-protanope Fahrer. Aus diesem Grund wird die vorerst etwas schwammige Frage formuliert:</p>
<p><strong>Sollte protanopen Menschen das Autofahren untersagt werden, da sie mehr Unfälle verursachen?</strong></p>
</div>
<div id="zielstellung" class="section level1">
<h1>Zielstellung</h1>
<p>Wenn protanope Autofahrer genau so fahren würden wie nicht-protanope Autofahrer, dann müsste der Anteil protanoper Unfallverursacher auch bei 1% liegen - also so wie in der Gesamtpopulation. (<em>Anmerkung: Bei Frauen ist der Anteil deutlich geringer, weswegen sich dieses gesamte Beispiel nur um männliche Fahrer dreht</em>) Da keine Daten zum Anteil protanoper Fahrer in vergangenen Auffahrunfällen erhoben wurden, müsste Geld investiert werden um dies in Zukunft für eine Stichprobe mit der Größe <span class="math inline">\(n\)</span> zu tun. Die Frage ist wie groß <span class="math inline">\(n\)</span> sein muss um nicht nur zu einem statistisch signifikanten, sondern auch praktisch relevanten Ergebnis zu kommen.</p>
<div id="erster-ansatz" class="section level2">
<h2>Erster Ansatz</h2>
<p>Es gilt also zu bestimmen welcher Anteil aller Auffahrunfälle von protanopen Fahrern verursacht wird und ob dieser erhöht ist. Wir könnten uns dafür entscheiden ein 95%-Konfidenzintervall mit einer von uns gewählten Breite um die jeweils ermittelte Wahrscheinlichkeit zu berechnen.</p>
<p>Die Formel zur Berechnung solch eines 95%-Konfidenzintervalls lautet</p>
<p><span class="math display">\[ p ± 1,96 \sqrt{\frac{p(1-p)}{n}}\]</span> wobei <span class="math inline">\(p\)</span> der Zielwahrscheinlichkeit entspricht (<em>Achtung! Hat nichts mit dem p-Wert zu tun!</em>). Diese Formel lässt sich auch nach <span class="math inline">\(n\)</span> umstellen, sodass wir eine Stichprobenmindestgröße erhalten mit der wir eine gewünschte Breite des 95%-Konfidenzintervalls um <span class="math inline">\(p\)</span> finden:</p>
<p><span class="math display">\[ n = 1,96^2 \frac{p(1-p)}{d^2} \]</span></p>
<p>wobei <span class="math inline">\(d\)</span> der halben Breite des angestrebten Konfidenzintervalls entspricht.</p>
<p>Würden wir nun also <span class="math inline">\(p=1\%=0,01\)</span> zusammen mit einer angestrebten halben Breite <span class="math inline">\(d=0,5\%=0,005\)</span> in die Formel einsetzen, so erhielten wir eine nötige Stichprobengröße von 1521.2736, aufgerundet also <span class="math inline">\(n=1522\)</span>:</p>
<pre class="r"><code>p &lt;- 0.01
d &lt;- 0.005</code></pre>
<div class="row">
<div class="col-md-6">
<pre class="r"><code>n &lt;- 1.96^2 * p*(1-p)/d^2
n</code></pre>
<pre><code>## [1] 1521.274</code></pre>
</div>
<div class="col-md-6">
<pre class="r"><code>ceiling(n)</code></pre>
<pre><code>## [1] 1522</code></pre>
</div>
</div>
<p>Wenn wir also 1522 Auffahrunfälle hinsichtlich der Protanopie des Unfallverursachers untersuchen würden, würde dies dazu führen, dass bei <span class="math inline">\(p=1\%\)</span>, alle Wahrscheinlichkeiten <span class="math inline">\(&lt;0,5\%\)</span> und <span class="math inline">\(&gt;1,5\%\)</span> nicht mehr im Konfidenzintervall lägen und somit auch signifikant verschieden von <span class="math inline">\(p\)</span> wären.</p>
<div class="row">
<div class="col-md-6">
<pre class="r"><code># Untere Grenze Konfidenzintervall [in %]
UKI &lt;- p - 1.96 * sqrt(p*(1-p)/n)
UKI*100</code></pre>
<pre><code>## [1] 0.5</code></pre>
</div>
<div class="col-md-6">
<pre class="r"><code># Obere Grenze Konfidenzintervall [in %]
OKI &lt;- p + 1.96 * sqrt(p*(1-p)/n)
OKI*100</code></pre>
<pre><code>## [1] 1.5</code></pre>
</div>
</div>
<pre class="r"><code># Breite Konfidenzintervall [in %]
(OKI-UKI)*100</code></pre>
<pre><code>## [1] 1</code></pre>
<p>Dies wirkt an sich schon wie ein solider Ansatz. Sicherlich sollte das <span class="math inline">\(d\)</span> nicht einfach so auf 0,5% gesetzt werden, sondern stattdessen eine Abweichung gewählt werden, die sich mit der Wissenschaft und dem Gesetz vereinbaren lässt. Mit anderen Worten: es muss ein in der Praxis relevanter Grenzwert gefunden werden, ab dem protanope Fahrer <em>bedeutend mehr</em> Unfälle verursachen als nicht-protanope Fahrer. Dies ist allerdings kein statistisches Thema und für den Rest dieses Szenarios werden wir weiterhin mit relevanten Abweichung von 0,5% arbeiten. Oder besser gesagt: ab einem Anteil protanoper Unfallverursacher über 1,5% sprechen wir davon, dass protanope Fahrer <em>bedeutend mehr</em> Unfälle verursachen als nicht-protanope Fahrer.</p>
<div id="mängel-des-ersten-ansatzes" class="section level3">
<h3>Mängel des ersten Ansatzes</h3>
<p>Selbst wenn wir uns darauf eingeschossen haben, dass eine Abweichung &gt; 0,5% bedeutsam wäre, weist unser Ansatz Mängel auf. So scheint die Tatsache, dass <span class="math inline">\(n=1522\)</span> eben nur für <span class="math inline">\(p=1\%\)</span> gilt, wenig hilfreich, wenn man länger darüber nachdenkt was zu prüfen ist. Würden wir in unserer Erhebung herausfinden, dass tatsächlich genau 1% aller Unfallverursacher protanop waren, dann wäre ein Blick auf das Konfidenzintervall völlig hinfällig. Interessant würde es ja erst dann, wenn der in der Stichprobe gefundene Anteil <span class="math inline">\(p_1\)</span> eben nicht bei 1%, sondern höher liegt. Und hier kommt die Crux: Bei <span class="math inline">\(n=1522\)</span> und einem gefundenen Anteil von z.B. <span class="math inline">\(p_1=1,51\%\)</span> (also mit einer Abweichung von mehr als 0,5% !) ergibt sich für das zugehörige 95%-Konfidenzintervall wie folgt:</p>
<pre class="r"><code>p.1 &lt;- 0.0151</code></pre>
<div class="row">
<div class="col-md-6">
<pre class="r"><code># Untere Grenze Konfidenzintervall [in %]
UKI.1 &lt;- p.1 - 1.96 * sqrt(p.1*(1-p.1)/n)
UKI.1*100</code></pre>
<pre><code>## [1] 0.8971743</code></pre>
</div>
<div class="col-md-6">
<pre class="r"><code># Obere Grenze Konfidenzintervall [in %]
OKI.1 &lt;- p.1 + 1.96 * sqrt(p.1*(1-p.1)/n)
OKI.1*100</code></pre>
<pre><code>## [1] 2.122826</code></pre>
</div>
</div>
<pre class="r"><code># Breite Konfidenzintervall [in %]
(OKI.1-UKI.1)*100</code></pre>
<pre><code>## [1] 1.225651</code></pre>
<p>Wie man sieht, führt ein bestimmtes <span class="math inline">\(n\)</span> nur für ein bestimmtes <span class="math inline">\(p\)</span> zur erwünschten Breite des Konfidenzintervalls. Je weiter sich der später tatsächlich gefundene Anteil <span class="math inline">\(p_1\)</span> vom für die Stichprobenplanung zugrundeliegenden Anteil <span class="math inline">\(p\)</span> unterscheidet, desto ungeeigneter ist auch die ursprünglich ermittelte Stichprobengröße <span class="math inline">\(n\)</span>. In diesem speziellen Fall, liegt der gefundene Anteil <span class="math inline">\(p_1=1,51\%\)</span> eigentlich mehr als 0,5% über den 1%, jedoch beginnt sein Konfidenzintervall schon bei 0,897%, sodass es die 1% noch mit einschließt und demnach <span class="math inline">\(p_1\)</span> nicht signifikant verschieden von 1% ist.</p>
<p><img src="stat_samplesize_files/figure-html/unnamed-chunk-11-1.png" width="576" style="display: block; margin: auto;" /></p>
</div>
</div>
</div>
<div id="zweiter-ansatz" class="section level1">
<h1>Zweiter Ansatz</h1>
<p>Zum Vergleich: Die Stichprobengröße, die nötig wäre um ein <span class="math inline">\(d=0,5\%\)</span> auch für <span class="math inline">\(p_1=1,51\%\)</span> einzuhalten, ergibt sich als</p>
<pre class="r"><code>n.1 &lt;- 1.96^2 * p.1*(1-p.1)/d^2
ceiling(n.1)</code></pre>
<pre><code>## [1] 2286</code></pre>
<p>Demnach wird eine größere Stichprobe benötigt, obwohl dieselbe Breite des Konfidenzintervalls angestrebt wird.</p>
<p>Nun wird also klar, dass es weder mit einem <span class="math inline">\(n=1522\)</span>, noch mit einem <span class="math inline">\(n=2286\)</span> getan ist. Das liegt daran, dass wir im Vorfeld keine Vorstellung davon haben in welchem Bereich sich der tatsächlich gefundene Anteil protanoper Unfallverursacher <span class="math inline">\(p_1\)</span> befinden wird. Klar ist nur, dass es erstrebenswert wäre, dass dessen Konfidenzintervall den Grenzwert <strong>nicht</strong> mit einschließt. Da es hier nur darum geht zu prüfen ob protanope Fahrer eine <em>erhöhte</em> Unfallwahrscheinlichkeit aufweisen, kann man es sogar noch vereinfachen: So wäre es - unabhängig davon wie groß <span class="math inline">\(p_1\)</span> ist - erstrebenswert, dass die untere Grenze von dessen Konfidenzintervall größer als der Grenzwert ist.</p>
<div id="umdenken" class="section level2">
<h2>Umdenken</h2>
<p>Wenn das gesetzt ist, fällt auf, dass uns auch die angestrebte Breite des Konfidenzintervalls nur indirekt interessiert. Was wir nämlich zu Beginn mit der praktisch relevanten Differenz (0,5%) bzw. dem Grenzwert (1,5%) versucht haben, wurde nicht so umgesetzt wie wir es eigentlich wollten.</p>
<p>Wenn wir wirklich glauben, dass ab einem Wert größer als dem Grenzwert 1,5%, der Anteil protanoper Unfallverursacher so viel zu hoch ist, dass sie nicht als gleichwertig sichere Fahrer eingestuft werden sollten, dann ist unser Zielwert, den wir gerne mit 95%iger Sicherheit ablehnen würden ja nicht 1%, sondern 1,5% - gegeben dem Fall, dass wir ein <span class="math inline">\(p_1\)</span> gefunden haben, dass &gt;1,5% ist. Was wir also eigentlich die ganze Zeit wollten ist, dass - unabhängig davon wie groß das letztendlich gefundene <span class="math inline">\(p_1\)</span> sein wird - wir eine so große Stichprobe erheben, dass die untere Grenze des Konfidenzintervalls von <span class="math inline">\(p_1\)</span> größer ist als 1,5%. <em>(Und nochmal zur Sicherheit: 1,5% ergibt sich aus den 1%, die wir im Normalfall finden würden plus einer von Experten gewählen praktisch relevanten Erhöhung um 0,5%)</em></p>
</div>
<div id="berechnung" class="section level2">
<h2>Berechnung</h2>
<p>Um diese Frage zu beantworten, wollen wir das Ganze für alle <span class="math inline">\(p_1\)</span> Werte ab 1,5% und bis 10,0% in 0,1%-Schritten durchrechnen (Infos zur Nutzung der packages <code>data.table</code> und <code>dplyr</code> gibt’s <a href="datr_moreadvanced.html">hier</a>)</p>
<pre class="r"><code>library(data.table)
library(dplyr)

get.n &lt;- data.table(p1.perc = seq(1.6, 10.0, 0.1)) %&gt;% # 1,6% - 10,0% in 0,01%-Schritten 
  mutate(p1     = p1.perc/100,
         d.perc = p1.perc - 1.5, # Differenz von p1 zum Grenzwert 1,5%
         d      =  d.perc/100,
         n      = ceiling((1.96^2 * p1 * (1-p1)) / d^2))</code></pre>
<div class="row">
<div class="col-md-6">
<pre class="r"><code>head(get.n) # erste 6 Zeilen</code></pre>
<pre><code>##    p1.perc    p1 d.perc     d     n
## 1:     1.6 0.016    0.1 0.001 60483
## 2:     1.7 0.017    0.2 0.002 16050
## 3:     1.8 0.018    0.3 0.003  7545
## 4:     1.9 0.019    0.4 0.004  4476
## 5:     2.0 0.020    0.5 0.005  3012
## 6:     2.1 0.021    0.6 0.006  2194</code></pre>
</div>
<div class="col-md-6">
<pre class="r"><code>tail(get.n) # letzte 6 Zeilen</code></pre>
<pre><code>##    p1.perc    p1 d.perc     d  n
## 1:     9.5 0.095    8.0 0.080 52
## 2:     9.6 0.096    8.1 0.081 51
## 3:     9.7 0.097    8.2 0.082 51
## 4:     9.8 0.098    8.3 0.083 50
## 5:     9.9 0.099    8.4 0.084 49
## 6:    10.0 0.100    8.5 0.085 48</code></pre>
</div>
</div>
</div>
<div id="ergebnis" class="section level2">
<h2>Ergebnis</h2>
<p>So bekommen wir also für all die möglichen <span class="math inline">\(p_1\)</span> ein entsprechendes <span class="math inline">\(n\)</span>, mit dem gegeben wäre, dass die untere Grenze des Konfidenzintervalls um <span class="math inline">\(p_1\)</span> über 1,5% liegt. In der ersten Zeile sehen wir, dass bei <span class="math inline">\(p_1=1,6\%\)</span> gut 60.000 Unfallversursacher untersucht werden müssten um die relativ kleine Abweichung von 0.1% über dem Grenzwert als statistisch abgesichert einstufen zu können. Es ergibt Sinn, dass bei <span class="math inline">\(p_1=10,0%\)</span> (letzte Zeile) nur 48 Unfallverursacher untersucht werden müssten um die große Abweichung von 8,5% als statistische signifikant zu identifzieren.</p>
<p>Mit diesen Berechnungen kann nun mit Experten darüber disktutiert werden was für eine Abweichung zu erwarten ist und wie groß die Stichprobe gewählt werden sollte.</p>
<p>Dies ist bereits das von uns angestrebte Ergebnis, wir wollen die Ergebnistabelle aber noch mit weiteren nützlichen Informationen füllen:</p>
<pre class="r"><code>get.n &lt;- get.n %&gt;%
  mutate(n.prot = ceiling(n*p1),                   # Absolute Anzahl protanoper Fahrer
         U.KI   = p1 - 1.96 * sqrt( p1*(1-p1)/n ), # Untere Grenze
         O.KI   = p1 + 1.96 * sqrt( p1*(1-p1)/n ), # Obere  Grenze
         RR     = round(p1/(1.0/100),1)) # Relatives Risiko (annäherungsweise)

head(get.n) # Erste 6 Zeilen</code></pre>
<pre><code>##    p1.perc    p1 d.perc     d     n n.prot       U.KI       O.KI  RR
## 1:     1.6 0.016    0.1 0.001 60483    968 0.01500001 0.01699999 1.6
## 2:     1.7 0.017    0.2 0.002 16050    273 0.01500005 0.01899995 1.7
## 3:     1.8 0.018    0.3 0.003  7545    136 0.01500002 0.02099998 1.8
## 4:     1.9 0.019    0.4 0.004  4476     86 0.01500035 0.02299965 1.9
## 5:     2.0 0.020    0.5 0.005  3012     61 0.01500015 0.02499985 2.0
## 6:     2.1 0.021    0.6 0.006  2194     47 0.01500017 0.02699983 2.1</code></pre>
<pre class="r"><code>tail(get.n) # Letzte 6 Zeilen</code></pre>
<pre><code>##    p1.perc    p1 d.perc     d  n n.prot       U.KI      O.KI   RR
## 1:     9.5 0.095    8.0 0.080 52      5 0.01530327 0.1746967  9.5
## 2:     9.6 0.096    8.1 0.081 51      5 0.01514799 0.1768520  9.6
## 3:     9.7 0.097    8.2 0.082 51      5 0.01577294 0.1782271  9.7
## 4:     9.8 0.098    8.3 0.083 50      5 0.01558858 0.1804114  9.8
## 5:     9.9 0.099    8.4 0.084 49      5 0.01537464 0.1826254  9.9
## 6:    10.0 0.100    8.5 0.085 48      5 0.01512951 0.1848705 10.0</code></pre>
<p>Die Spalte <code>n.prot</code> gibt die Anzahl protanoper Fahrer an, die in der Stichprobe mit Größe <span class="math inline">\(n\)</span> dem Anteil <span class="math inline">\(p_1\)</span> entspricht. Bezogen auf die erste Zeile bedeutet das: wenn mindestens 968 der 60.483 Unfallverursacher protanop wären, dann entspräche dies einem <span class="math inline">\(p_1\)</span> von mindestens 1,6% und dessen untere Grenze des Konfidenzintervalls würde die 1,5% nicht mehr miteinschließen (siehe auch Spalte <code>U.KI</code>).</p>
<p>Das Relative Risiko (Risk Ratio), auf das hier nur sehr kurz eingegangen werden soll (mehr Infos z.B. <a href="https://www.wikiwand.com/de/Relatives_Risiko">hier</a>), wurde hier zusätzlich und nur annäherungsweise geschätzt. Die Annäherung rührt daher, dass man für dieses Maß auch den Anteil protanoper Männer an Autofahrern <em>ohne</em> Unfall benötigt. Dieser wurde zur Berechnung einfach auf die 1% gesetzt, was hier übrigens dazu führt, dass <span class="math inline">\(RR=p_1\)</span>. Ein relatives Risiko von 2 würde bedeuten, dass das Risiko einen Unfall zu verursachen unter protanopen Autofahrern 2-mal so hoch ist wie unter nicht-protanopen Autofahrern.</p>
</div>
<div id="graphische-darstellung" class="section level2">
<h2>Graphische Darstellung</h2>
<p>Diese Ergebnisse sollen schließlich noch grafisch dargestellt werden:</p>
<p><img src="stat_samplesize_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Und hier eine detaillierte Erklärung zur Erstellung des Plots mit den packages <code>ggplot2</code> und <code>ggrepel</code>. Bevor wir die Ergebnisse plotten, erstellen wir aus ihnen einen Teildatensatz mit einer Hand voll markanter Werte, die wir im Plot extra hervorheben wollen:</p>
<pre class="r"><code>label.tab &lt;- get.n %&gt;%
  filter(p1.perc %in% c(2.5, 3, 5, 8)) %&gt;% # Auswahl dieser 4 Werte
  select(n, p1.perc, RR) %&gt;% # Behalte nur relevante Spalten
  mutate(labeltext = paste0(&quot;n=&quot;,n,&quot;; RR=&quot;, RR)) # Erstellen eines Labels für jeden Wert

label.tab</code></pre>
<pre><code>##      n p1.perc  RR     labeltext
## 1: 937     2.5 2.5 n=937; RR=2.5
## 2: 497     3.0 3.0   n=497; RR=3
## 3: 149     5.0 5.0   n=149; RR=5
## 4:  67     8.0 8.0    n=67; RR=8</code></pre>
<p>Der Plot wurde mit folgendem Code erstellt:</p>
<pre class="r"><code>library(ggplot2)
library(ggrepel) # package um einzelne Datenpunkte in einem Plot mit einem Label zu versehen

ggplot() + 
  # Vertikale Linie bei 1.0%
  geom_vline(xintercept=1.0, linetype=&quot;dashed&quot;, color=&quot;#00923F&quot;, alpha=0.5) + 
  # Label neben der vertikalen Linie (bei 0.8%)
  geom_text(aes(x=0.8, y=750, label=paste0(&quot;Anteil protanoper Männer (p=1.0%)&quot;)), 
            colour=&quot;#00923F&quot;, angle=90, alpha=0.5) + 
  # Vertikale Linie bei 1.5%
  geom_vline(xintercept=1.5, linetype=&quot;solid&quot;, color=&quot;#00923F&quot;) + 
  # Label neben der vertikalen Linie (bei 1.3%)
  geom_text(aes(x=1.3, y=750, label=paste0(&quot;Biologisch relevanter Grenzwert* (1.5%)&quot;)), 
            colour=&quot;#00923F&quot;, angle=90) + 
  # Linie für alle ermittelten n (data=get.n)
  geom_line(data=get.n, aes(y=n, x=p1.perc), color=&quot;#00923F&quot;) + 
  # Punkte nur für ausgewählte n (data=label.tab)
  geom_point(data=label.tab, aes(y=n, x=p1.perc), color=&quot;#00923F&quot;) + 
  # Punkte-Label nur für ausgewählte n (data=label.tab)
  geom_text_repel(data=label.tab, aes(y=n, x=p1.perc, label=labeltext), 
                  nudge_x = 0.2, nudge_y = 10, vjust=0, hjust=0) + 
  # Formatiere x-Achse
  scale_x_continuous(name = paste0(&quot;Gefundener Anteil protanoper Unfallverursacher (p1) [%]&quot;), 
                     breaks = seq(0,10,1), limits = c(0,10)) + 
  # Formatiere y-Achse
  scale_y_continuous(name = paste0(&quot;Stichprobengröße (n), bei dem das 95%-Konfidenzinterval vom\n gefundenen Anteil protanoper Unfallverursacher (p1) \n den biologisch relevanten Grenzwert von 1.5% nicht enthält&quot;), breaks = c(0,50,100,150,200,250,400,600,800,1000, 1500), limits = c(0,1500)) + 
  # Title und Anmerkung unterm Plot
  labs(title    = &quot;Stichprobenplanung zur Untersuchung protanoper Unfallverursacher&quot;,
       caption  = &quot;*Der biologisch relevante Grenzwert ergibt sich aus\n dem erwarteten Anteil protanoper Unfallverursacher (1.0%) + der selbst gewählten Differenz (0.5%) = 1.5%.\n Das relative Risiko (RR) wurde hier nur annäherungsweise geschätzt,\n indem ein Anteil protanoper Autofahrer ohne Unfall von 1.0% angenommen wurde.&quot;) + 
  # Formatvorlage (Hintergrundfarbe usw.)
  theme_bw() + 
  # Zeige nur die Hilfslinien an, die auch Werte an den Achsen haben
  theme(panel.grid.minor = element_blank())</code></pre>
</div>
</div>

&nbsp;
<hr />
<p style="text-align: center;">Bei Fragen kannst du mir gerne schreiben!</p>
<p style="text-align: center;"><span style="color: #808080;"><em>schmidtpaul@hotmail.de</em></span></p>

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- Add font awesome icons -->
<p style="text-align: center;">
    <a href="https://www.researchgate.net/profile/Paul_Schmidt17/research" class="fa fa-pencil"></a>
    <a href="https://www.linkedin.com/in/schmidtpaul1989/" class="fa fa-linkedin"></a>
    <a href="https://www.xing.com/profile/Paul_Schmidt203/cv/" class="fa fa-xing"></a>
    <a href="https://github.com/SchmidtPaul/" class="fa fa-github"></a>
</p>

<a href="https://hits.seeyoufarm.com"><img src="https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=https%3A%2F%2Fschmidtpaul.github.io%2FcrashcouRse%2F&count_bg=%23003F75&title_bg=%23555555&icon=&icon_color=%23E7E7E7&title=hits&edge_flat=false" class="center"/></a>

&nbsp;


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
